// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBigsgFazYLCqPJ773OmYTjSwzhDomW_hU',
    appId: '1:1076720265070:android:188d248edf69a6e86c037f',
    messagingSenderId: '1076720265070',
    projectId: 'tarimtek-1adec',
    storageBucket: 'tarimtek-1adec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdSHMMQRyIXzORkkjO0Gb__Xe4ODFdVLk',
    appId: '1:1076720265070:ios:1eabdc9a3a3948e36c037f',
    messagingSenderId: '1076720265070',
    projectId: 'tarimtek-1adec',
    storageBucket: 'tarimtek-1adec.appspot.com',
    iosBundleId: 'com.example.tarimtek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsbhVJZnBExR4xrmjLGOyTxmZXstLQtQs',
    appId: '1:1076720265070:web:bc4ce182a0a116806c037f',
    messagingSenderId: '1076720265070',
    projectId: 'tarimtek-1adec',
    authDomain: 'tarimtek-1adec.firebaseapp.com',
    storageBucket: 'tarimtek-1adec.appspot.com',
    measurementId: 'G-ZH84WXB7BS',
  );
}
